# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Louisiana Biomedical Research Network
description: LBRN is a collaborative network, organized to enhance the quality of biomedical research conducted throughout the state of Louisiana.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lbrn.lsu.edu" # the base hostname & protocol for your site, e.g. http://example.com
github_username: johnqlsu

collections_dir: site_collection
collections:
  news:
    output:
  project_investigators:
    output: true
  old_pi:
    output:
  events:
  admin_core:
    output:
  bbc_core:
    output:
  committee-members:
    output:
  LBRN_Steering_Committee:
    output:
  MCBR_core:
    output:
  partner_Institutes:
    output:
  previous_pis:
    output: true


# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
exclude:
  # - Gemfile
  # - Gemfile.lock
#Server settings
port: 4000
encoding: utf-8
include: ['.htaccess']
